Initial report commit
uk-tre/website pull request #28
Opened 2023-11-30 16:41 UTC by harisood

2023-12-19 18:56 UTC, harisood commented
Ugh Idk why that link check is failing, @manics any ideas?

2024-01-22 15:27 UTC, Davsarper reviewed
No time for 3 last files so will come back to it:
- Need anonymisation
- Some copy pasted format causing issues, made the neessary suggestions I hope
- Took out images of handwritten notes, they make it too long

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-data-harmonisation.md
> +- Sarah Stewart
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-data-harmonisation.md
> +Transcription of the above by David:
```suggestion
Transcripted by CMWG team
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-multi-tre-analysis.md
> +- Participants: Fatemeh Torabi, Guneet (Uni of Dundee), Calum Macdonald, Peter Maccallum
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-multi-tre-analysis.md
> +-- rethink of data holdings and services from Data Warehouses to Data Fabrics.
```suggestion
**Short term**: understanding what we have
- Define what is a TRE, wrt to **multiple** TREs within a PEST framework that highlights issues that are not just technical, for example includes the diversity of TRE models, the business models of TREs, where risk, responsibility and accountability lay, and includes certifiable PROCESS as a core pillar (shared SOPs). Multi-TREs require new Processes.
- Define a TRE Maturity Model that builds on above to develop a more objective model of TRUST, RISK and RESPONSIBILITY for inter-TRE data exchange. Could be used to assess, compare, and facilitate trust between TREs.
- A common language scale for the ‘tiers’ of TREs suitable for different levels of inter-TRE sensitivity.
- Identify and clarify PEST bottlenecks with examples

**Medium Term**: shifting to newer ways
- Review different architectures and processes for working between TREs
- What would be just enough with what we already have (e.g. 5SROCrate as m-TRE middleware using current processes)
- What m-TRE processes would we need to introduce
- The role of trusted intermediaries (brokers, federated analytics services) to take on risk and responsibility and reposition the Data Sharing Agreements. e.g global identity services linking identities and records, who takes responsibility?

**Long Term**: radical shift
- PPIE education outside the PPIE self selecting bubble to counter mistrust of government and conspiracy theory
- Expectation that data is owned by the NHS?
- Rethink of data holdings and services from Data Warehouses to Data Fabrics.
```
Was not fully clear ot me the format that we wanted here, but looked odd

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-multi-tre-analysis.md
> +  -- Networks of secure data services based on Enterprise data models.
```suggestion
- What is a TRE ?  
  - Are they always repositories for single datasets, popup TRE?
  - Not always - many of the environments have multiple users and projects on top of the core dataset, through project-based access through VMs/virtual desktops.
  - There is also a requirement for high performance computing for some datatypes (GPU for AI/imaging, workflows etc)
- Do we need federation? Can we avoid multiple TREs?
  - Governance requirements vary between data classes - you may need TREs to meet each governance requirements.
  - But each TRE is expensive to run, especially assurance, governance, data egress control.
- How do TREs know they can trust each other?
  - When workflows have to be shared between environments, it is easier to share between those with similar accreditations - e.g ISO27001.
  - Federating TREs requires interoperability at the process level, shared SOPs etc.
  - There will be many TREs built from the technological parts - but if there are poorly run ones, they will damage the whole 'brand' and impact on all TRE operators. More TREs, more risk.
  - A 'maturity model' could be used to assess, compare, and facilitate trust between TREs.
  - Legal obligations on indvidual TRE providers act as a strong constraint on data sharing; but a common list of questions might help.
- Can we develop a new brokered distributed/federated anaytics model?
  - We need a new model to allow this.
  - TRE-FX type solutions need to be driven by TREs.
  - Need a common language scale for the 'tiers' of TREs suitable for different levels of sensitivity.
  - People need to query across datasets - there are few cases where you can answer the research question without linking identities and records.
  - But a global identity connecting service would be a huge responsibility.
- How do we carry the public with us?
  - Estonia have an opt-out system for health records, opt-in for genomics data; but when public confidence drops, opt-outs increase.
  - Public perception of risk is a problem.
  - In COVID, people were happy to share data.
  - Even trust in NHS is not universal now...
  - Education outside the TRE 'bubble' to counteract conspiracy theories etc.
- Do trusted data fabrics offer a different view?
  - Networks of secure data services based on Enterprise data models.
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-nhs-sdes.md
> +- Seb Bacon
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-nhs-sdes.md
> +![image](https://hackmd.io/_uploads/rkvFohEHa.png)
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-ppie.md
> +- Ballint
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-ppie.md
> +This discussion was an informative discussion that moslty gave the opportunity for attendees to ask PPIE experts about their experience so far.
```suggestion
This discussion was an informative discussion that mostly gave the opportunity for attendees to ask PPIE experts about their experience so far.
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-ppie.md
> +  Training and support ofhow to communicate with members of the public for academics and 'technicians'
```suggestion
- What resources would be needed (people, time, funds, infrastructure etc.)?
 - Funding to recruit members of the public who might not normally get involved. Examples of using Sortition and Coal Rabie and IPSOS
 - Utilising that expertise of external recruitment agencies
 - Training and support ofhow to communicate with members of the public for academics and 'technicians'
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-ppie.md
> +  Embedding PIE skills in peoples careers
```suggestion
  - TRE specific PIE groups
  - Embedding PIE skills in peoples careers
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-python-r-package-import.md
> +
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-python-r-package-import.md
> +
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-satre.md
> +- Cat Morris
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-sight-unseen.md
> +- X
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-sight-unseen.md
> +- X
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-standardisation-tensions.md
> +- ![image](https://hackmd.io/_uploads/rypxXhEHa.png)
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-standardisation-tensions.md
> +![image](https://hackmd.io/_uploads/HJ5QbhErT.png)
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-standardisation-tensions.md
> +By David from photo
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-standardisation-tensions.md
> +![image](https://hackmd.io/_uploads/Sk9RG3NB6.png)
```suggestion
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-standardisation-tensions.md
> +
```suggestion
Transcripted by CMWG

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +- Thomas Tamblyn - Statistical Support officer (ingress and egress)
```suggestion
```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +---
```suggestion

```

2024-01-22 15:27 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Round 2
```suggestion
This breakout room continued during the second round
```

2024-01-23 16:12 UTC, Davsarper requested changes
final 3 files reviewd, also made suggestions to take out the title 'Attendees' where I had failed to do so.

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Individual researchers and work with them and the RO.
```suggestion
- UKBB core underpinning funding
- Fund TREs for 3-5 years for specific projects
- Specific use cases not currently supported
- Individual researchers and work with them and the RO.
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +?Provide underpinning capacity?
```suggestion
- Free at the point of use funding?
- Provide underpinning capacity?
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Trying to enable research
```suggestion
- Free at point of access
- Don't know how the budget is secured
- Funding comes through different sources ADR UK
- Research proposal, existing staff funding or contracted.
- For commercial and public researchers usage has to be for public good, commit to publishing and not for profit
- Virtual machines provided some policy for standardising storage/compute available
- Trying to enable research
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Universities also fund
```suggestion
- Intrinsic limit on budget call
- Budget for a specific network/platform
- Leverage external investment
- Some Pharma match funding
- Universities also fund
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Hub large funding but cliff-edged
```suggestion
Move to long term funding
- Strategic level of funding, buffered from long-term budget
- Hub large funding but cliff-edged
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Power users can over-consume, less accountability not having to justify use
```suggestion
- Incentivised-disinsentivised, equity of access
- Power users can over-consume, less accountability not having to justify use
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +reminder: Don't offer data for commercial use
```suggestion
- Free at point of access so data is freely accessible
- Reminder: Don't offer data for commercial use
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +All TREs have these issues, share the solutions
```suggestion
- Ingress-egress labour intensive to pour human eyes
- Automation tools for validating statistical disclosure test
- Skilled job
- Tools and more people-more efficient tools; more people would always be good.
- All TREs have these issues, share the solutions
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Free at point of use?? Cuts out some of the applications automated validation of inputs
```suggestion
- Free at point of use?? Cuts out some of the applications automated validation of inputs
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Sustainability, prime an initiative without committing to long term investment
```suggestion
- Fix one part and it just shows the next bottleneck
- Fraunhoffer 1/3-1/3-1/3 lights_on-academic-commercial_activity
- Sustainability, prime an initiative without committing to long term investment
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +DARE UK would create a TRE to handle data as an offering
```suggestion
- Focus critical mass on small number
- DARE UK would create a TRE to handle data as an offering
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +TT: At the point at which you have seamless transition between TREs?
```suggestion
- At what point does a federated TRE network become a single TRE?
- TT: At the point at which you have seamless transition between TREs?
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +  - Why do this has to be part of retaining people
```suggestion
  - Why doing this has to be part of retaining people
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +  - Localising staff makes this easier, centrally models push more to thinking about pay
```suggestion
  - Localising staff makes this easier, central models push more to thinking about pay
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +  - Consultatancy
```suggestion
  - Consultancy
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +  CSP platform neutral certifications for Data/Cloud
```suggestion
  - Chartered research infrastructure?
  - CSP platform neutral certifications for Data/Cloud
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +People:
```suggestion

People:
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Developing things to deal with core use case
```suggestion
- VDI, Excel may be R, Stata
- Developing things to deal with core use case
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Good training for Data scientists: SC like training relevant to disciplines
```suggestion
- Good training for Data scientists: SC like training relevant to disciplines
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Bill after usage is best, but challenging for proposal/funding
```suggestion
- Not sustainable to go consistently over budget
- Bill after usage is best, but challenging for proposal/funding
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Why different for UCL TRE?
```suggestion
- Why different for UCL TRE?
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Different environments work differently from researcher perspective
```suggestion
- Different environments work differently from researcher perspective
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Duties imposed as data controllers law, or interpretation runs counter to wants of researchers
```suggestion
- Duties imposed as data controllers law, or interpretation runs counter to wants of researchers
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +More paperwork to create and chase invoices.
```suggestion
- More paperwork to create and chase invoices.
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Difference between model for internal and external users.
```suggestion
- Difference between model for internal and external users.
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Constrain in the cloud?
```suggestion
- How costing then? Free at point of use, cost distributed against overheads.
- Constrain in the cloud?
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +Service in place, refreshed but need to appear to do something different each time to secure funding.
```suggestion
- Service in place, refreshed but need to appear to do something different each time to secure funding.
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-tre-sustainability-and-operations.md
> +But what are things going to look like in 5 years time
```suggestion
- But what are things going to look like in 5 years time
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/index.md
> +The morning talks were broadcast online for those that could not in person, but all afternoon sessions including breakout discussions were in-person only.
```suggestion
The morning talks were broadcast online for those that could not attend in person, but all afternoon sessions including breakout discussions were in-person only.
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/index.md
> +- Data Accress Request Form
```suggestion
- Data Access Request Form
```

2024-01-25 13:14 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/index.md
> +The session ended with a short Q&A, which can be found on the [recording of the session](https://www.youtube.com/watch?v=ipfU4FdjYGM).
If you know the timestamp we can include it in the link (append`&t=<MINUTES>m<SECONDS>s`

2024-01-25 13:18 UTC, Davsarper commented on docs/events/wg_workshops/2023-09-04-september-meeting/index.md
> +The session ended with a short Q&A, which can be found on the [recording of the session](https://www.youtube.com/watch?v=ipfU4FdjYGM).
We included "chapters" in the video
[00:00](https://www.youtube.com/watch?v=ipfU4FdjYGM&t=0s) Introduction
[03:57](https://www.youtube.com/watch?v=ipfU4FdjYGM&t=237s) DARE UK updates
[09:05](https://www.youtube.com/watch?v=ipfU4FdjYGM&t=545s) Keynote by Emily Jefferson
[44:46](https://www.youtube.com/watch?v=ipfU4FdjYGM&t=2686s) Q&A
[51:16](https://www.youtube.com/watch?v=ipfU4FdjYGM&t=3076s) Next steps for the day

2024-01-25 14:04 UTC, manics commented
```
(events/wg_workshops/2023-09-04-september-meeting/index: line   36) broken    https://www.turing.ac.uk/ - 403 Client Error: Forbidden for url: https://www.turing.ac.uk/
```
I suspect the Turing website is treating GitHub link checks as suspicious traffic and blocking it

2024-01-25 14:08 UTC, Davsarper commented
> I suspect the Turing website is treating GitHub link checks as suspicious traffic and blocking it
That would be very Turing, @JimMadge have you had a similar issue before?

2024-01-25 14:34 UTC, manics commented
This PR is too big and has been open too long :smile:

I think the best approach now is to get any final changes in, and when we're happy with the content I'll rebase this branch, squash, and force push, to remove all history (so we'll end up with a single commit) before merging

2024-01-25 14:39 UTC, Davsarper commented
Definitely! I am now struggling with changes from everyone. Agreed, let's finalise content which I think we are happy with? I will approve your suggestions @manics they all LGTM

2024-01-25 14:56 UTC, manics commented
I've marked this as draft as a reminder to force push/rebase to remove the history. I'll do that as soon as someone tells me to 😄

2024-01-25 15:01 UTC, Davsarper reviewed
Harmonised title hierarchy: roadmap and quesitons were someitmes wihtin raw notes sometimes not, they should be as they are titles from the hackmd templates

2024-01-25 15:40 UTC, Davsarper approved these changes

2024-01-25 15:49 UTC, manics commented on docs/events/wg_workshops/2023-09-04-september-meeting/breakout-sessions.md
> +:maxdepth: 0
```suggestion
:maxdepth: 1
```
`maxdepth: 0` means create an internal TOC but don't show it.

2024-01-26 11:50 UTC, JimMadge commented
> > I suspect the Turing website is treating GitHub link checks as suspicious traffic and blocking it
> 
> That would be very Turing, @JimMadge have you had a similar issue before?

Yes, not just GitHub. In general I don't think I've found a link checker that works out of the box. I think the webserver rejects requests that don't have the headers saying they are a browser. It might work if you spoof Firefox, for example. But I generally add `*turing.ac.uk` to my exclude list :smile:.

2024-01-29 13:38 UTC, manics approved these changes
![image](https://github.com/uk-tre/website/assets/1644105/b317e96c-414e-4bd4-aea7-20cf01d0fc6f)

2024-01-29 13:42 UTC, harisood commented
Apologies if my 'this works for me' file naming and structure made this harder than it needed to be... and if it did plz lmk how to improve in the future!

2024-01-30 11:09 UTC, merged