December report
uk-tre/website pull request #35
Opened 2023-12-13 17:16 UTC by harisood

2023-12-18 17:28 UTC, harisood commented
@manics @Davsarper bar the links I think this is ready for review!

2024-01-22 12:55 UTC, Davsarper requested changes

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/discussion-tre-federation.md
> +- Propose a high-level federation WG (IG?) as an umbrella/place to start, using the UK TRE/DARE UK/RDA model
An action here or not? given the time it takes us to process report there should be a more immediate action to follow up on these

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
>  A talk by the Community Management working group on the latest developments, funding and plans for the community.
```suggestion
A talk by the Community Management Working Group on the latest developments, funding and plans for the community.
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +```{toctree}
in preview this is not showing correctly to me, or rather the whole thing is visible which I am not sure it should. Sorry I am not more useful

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +AWS are revamping their TRE offerings. They have a new open-source product "Research Engineering Studio" which replaces https://github.com/awslabs/service-workbench-on-aws
```suggestion
AWS are revamping their TRE offerings.
They have a new open-source product "Research Engineering Studio" which replaces https://github.com/awslabs/service-workbench-on-aws
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-automated-output-checking-coi.md
>  The session is intended to give an over view of the Community of Interest on automated risk assessment.
```suggestion
The session is intended to give an overview of the Community of Interest on automated risk assessment.
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-manual-output-checking.md
> +  - Options such as Azure Cognitive Seach have been used successfully in the financial sector previously to look for individual PII.
```suggestion
  - Options such as Azure Cognitive Seacrh have been used successfully in the financial sector previously to look for individual PII.
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-researcher-passports.md
> +Further discussions centred around processes to interrogate validity of researcher records, how to record 'untrustworthy' researchers, and how to accommodate different levels of permission for differ
```suggestion
Further discussions centred around processes to interrogate validity of researcher records, how to record 'untrustworthy' researchers, and how to accommodate different levels of permission for different researchers, depending on how sensitive the project they are working on is.
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Led by HIC, Dundee; Alan Turing; UCL
```suggestion
- Led by HIC, Dundee; The Alan Turing Institute; UCL
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Leanr and explore
```suggestion
- Learn and explore
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Great that SATRE invovled public, reflect this in the specification would be good for funding, and to highlight directly in the specifications where the project has reflected public/patient request
```suggestion
- Great that SATRE involved public, reflect this in the specification would be good for funding, and to highlight directly in the specifications where the project has reflected public/patient requests.
```

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +This workshop introduced the idea of TREs within local council work, making specific reference to the London NHS SNSDE, and how Structurizr can be used for rendering C4 diagrams of data architecture.
Is Structurizr known enough that is needs no explanaiton to distinguish its name from a typo?
Could add this link for clarity (if this is indeed the right thing) https://github.com/uk-tre/community-management/issues/55

2024-01-22 12:55 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +- X
```suggestion
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Great that SATRE invovled public, reflect this in the specification would be good for funding, and to highlight directly in the specifications where the project has reflected public/patient request
```suggestion
- Great that SATRE involved public, reflecting this in the specification would be good for funding, and to highlight directly in the specifications where the project has reflected public/patient requests.
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Build on public engagement, on that angle, nature of spec neeeds be broad and high level, important in the public engagment section. Overlaps with other work in the wider community.
```suggestion
- Build on public engagement, on that angle, nature of spec neeeds be broad and high level, important in the public engagement section. Overlaps with other work in the wider community.
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Another call for the SATRE working group before Christmas to be ready for January and identify key prioirities
```suggestion
- Another call for the SATRE working group before Christmas to be ready for January and identify key priorities
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- Happy to share what they are doing with the SATRE team to get feedback on theri approach
```suggestion
- Happy to share what they are doing with the SATRE team to get feedback on their approach
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +How do SDE Accreditation framework from UKSA and SATRE fit together?
```suggestion
How do SDE Accreditation frameworks from UKSA and SATRE fit together?
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- NWSDE are doing SATREfication of their TRE using github rather than spreadsheet
```suggestion
- NWSDE are doing SATREfication of their TRE using GitHub rather than spreadsheet
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- The SATRE pointing system could have subsection SATRE-PPI scoring how many of the public requirements are being met
```suggestion
- The SATRE scoring system could have subsection SATRE-PPI scoring how many of the public requirements are being met
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-satre.md
> +- CC nomiated as chair to lead SATRE working group and explore means of succession funding
```suggestion
- CC nominated as chair to lead SATRE working group and explore means of succession funding
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +- Brief introduction of London Borough of Tower Hamlets and Health Determinants Research Collaboration( HDRC)
```suggestion
- Brief introduction of London Borough of Tower Hamlets and Health Determinants Research Collaboration (HDRC)
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +  - To comply with the data governance, the linked dataset (administrative and NHS data) needs to be stored in data haven that are accrediated.
```suggestion
  - To comply with the data governance, the linked dataset (administrative and NHS data) needs to be stored in data haven that are accredited.
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +  - Such challenge in data storage and handling make it difficult to facilitate a collaborative research environment under the current data system.
```suggestion
  - Such challenges in data storage and handling make it difficult to facilitate a collaborative research environment under the current data system.
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +  - AS such, TRE provides a possible solution to offer a playground/ sandbox to allow researchers from council, community, academia and etc. to access and analyse the dataset.
```suggestion
  - As such, TRE provides a possible solution to offer a playground/ sandbox to allow researchers from council, community, academia etc. to access and analyse the dataset.
```

2024-01-25 11:09 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/workshop-tre-c4-architecture.md
> +  11
```suggestion
```

2024-01-30 13:34 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +:maxdepth: 0
```suggestion
:maxdepth: 1
```

2024-01-30 14:07 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/discussion-tre-federation.md
> +- Propose a high-level federation WG (IG?) as an umbrella/place to start, using the UK TRE/DARE UK/RDA model
I presume Rob will be the one to propose this, or at least will ne heavily involved, so I think we can discuss this separately

2024-01-30 14:07 UTC, manics commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +More detail can be found in the [our focus section]()
```suggestion
```
Shall we take this out, merge, and add it in later?

2024-01-30 17:21 UTC, Davsarper commented
Uploaded to Zenodo, pending approval, once I have that will update the link that is missing and slightly rephrase that sentence. Then approve? I think all other conversations are outdated or resolved no?

2024-01-30 17:23 UTC, manics commented
https://zenodo.org/records/10593493

2024-01-31 09:39 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +More detail can be found in the [our focus section]()
```suggestion
More detail can be found in the [full proposal](https://zenodo.org/records/10593493)
```

2024-01-31 09:41 UTC, Davsarper commented on docs/events/wg_workshops/2023-12-05-december-meeting/index.md
> +More detail can be found in the [our focus section]()
I have suggested to just link to the full proposal

2024-01-31 09:49 UTC, Davsarper approved these changes

2024-01-31 11:51 UTC, manics commented
This is still marked as draft, what's left to do that can't wait?

2024-01-31 11:58 UTC, Davsarper commented
With the updated link I think it is ready, admitedly lost track of some suggested changes but I think they are all applied. I would approve, merge, and if we spot anything fix in a new PR

2024-01-31 12:01 UTC, manics approved these changes

2024-01-31 12:01 UTC, merged

2024-01-31 12:07 UTC, Davsarper commented
[heart]         David Sarmiento Perez reacted to your message:
________________________________
From: Simon Li ***@***.***>
Sent: Wednesday, January 31, 2024 12:01:18 PM
To: uk-tre/website ***@***.***>
Cc: David Sarmiento Perez ***@***.***>; Mention ***@***.***>
Subject: Re: [uk-tre/website] December report (PR #35)


Merged #35<https://github.com/uk-tre/website/pull/35> into main.

—
Reply to this email directly, view it on GitHub<https://github.com/uk-tre/website/pull/35#event-11654810999>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A4LZQ6EMBMNQDXDRAV5TPF3YRIXA5AVCNFSM6AAAAABATQSWGOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGY2TIOBRGA4TSOI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>